version: "3.8"
services:
  api:
    container_name: api
    build: ./infra/node
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /api
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db/data:/var/lib/mysql